### ISSUE TITLE
Add assets/images folders

### ISSUE THREAD

**Issue by Yodart** [Yodart/movapp-mobile-app#14]
Create the `assets` and `images` (inside of assets) folders on https://github.com/Yodart/movapp-mobile-app/tree/development . Then import both on https://github.com/Yodart/movapp-mobile-app/blob/development/pubspec.yaml
- [x] `assets` folder is in the root folder
- [x] `images` folder is inside of `assets`
- [x] both files are imported to `pubspec.yaml`

**Comment by Marchesotti** [comment]
`images` was added to `assets`, wich was added to root folder. Both imported to `pubspec.yaml`
