### ISSUE TITLE
Bill Class

### ISSUE THREAD

**Issue by Yodart** [Yodart/movapp-mobile-app#22]
Create bill class as in `lib/Cache/BillClass.dart`, the class should have the follwing:
- Build arguments (all required):
code, value,issue date, payment date,  payer (instance of `User`), status

**Comment by Marchesotti** [comment]
Created `BillClass.dart` in `lib/Cache/`. 
`BillClass.dart` contains `billCode`, `billValue`, `billIssueDate`, `billPaymentDate`, `billPayer`, `billStatus`.
Done in #29
