### ISSUE TITLE
Bill Class Update

### ISSUE THREAD

**Issue by Yodart** [Yodart/movapp-mobile-app#31]
Bill Class:
- [x] int billCode should be a String
- [x] int billValue should be a double
- [x] String billIssueDate should be of type Datetime
- [x] String billPaymentDate should be fo type Datetime
- [x] User billPayer;
- [x] bool billStatus should be renamed to `billPaymentStatus`

**Comment by Marchesotti** [comment]
Updated `BillClass.dart`.
`billCode` is now `String`.
`billValue` is now `double`.
`billIssuaDate` and `billPaymentDate` are now `DateTime`.
`billStatus` renamed to `billPaymentStatus`.
