### ISSUE TITLE
Welcome Screen Componentization

### ISSUE THREAD

**Issue by Yodart** [Yodart/movapp-mobile-app#35]
The following widgets should turn into widgets under `lib/Welcome/Widgets/`:
- [x] `LoginButton.dart`
- [x] `Logo.dart`
- [x] `WelcomeTitle.dart`
- [x] `WelcomeSubtitle.dart`
- [x] `ContinueWithInstagram.dart`*
*should contain both the button and the text below, so the entire column should be selected
- [x] `CreateAccountButton.dart`
- [x] `Footer.dart`

**Comment by Yodart** [comment]
Proceedure to follow:
- Copy and paste de standard code
- Change de name from `WidgetName` to the desired widget name
- Paste de actual widget under line 17
- Import the newly built widget to the Screen file passing `constraints` under the `parentConstraints` argument

**Comment by Marchesotti** [comment]
Created in `lib/Welcome/Widgets/`:
`LoginButton.dart`, `Logo.dart`, `WelcomeTitle.dart`, `WelcomeSubtitle.dart`, `ContinueWithInstagram.dart`, `CreateAccountButton.dart`, `Footer.dart`.

Widgets imported to `WelcomeScreen.dart`.

Done in #36
